version: 2.1

executors:
  docker-container:
    docker:
      - image: cimg/node:20.13.0

jobs:
  build_and_deploy:
    executor: docker-container
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm i
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Compress .tar.gz
          command: |
            tar -czvf devision.tech.tar.gz devision.tech
      - add_ssh_keys:
          fingerprints:
            - "SHA256:KZtig5dHjW53fw8A3R1UbBLAtvP0SQ/0Aih+3FpYBWI"
      - run:
          name: Add known host
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Upload via scp
          command: |
            scp devision.tech.tar.gz $SSH_USER@$SSH_HOST:/root/usr/share/apps
      - run:
          name: Extract and deploy via ssh
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /root/usr/share/apps && tar -xzvf devision.tech.tar.gz"

workflows:
  deploy:
    jobs:
      - build_and_deploy:
          context:
            - build-context
# https://circleci.com/docs/deploy-over-ssh/
# https://circleci.com/docs/configuration-reference/#add-ssh-keys

# ssh key
# locally
# cd ~/.ssh
# ssh-keygen -t ed25519 -C "ralph.metel@gmx.de"
# on prod server
# echo "public-key" >> authorized_keys
