version: "3"

services:
  metzner-nginx:
    container_name: metzner-nginx
    image: metzner-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - metzner-frontend
      - metzner-backend
    networks:
      - metzner-app

  metzner-frontend:
    container_name: metzner-frontend
    image: metzner-frontend
    ports:
      - "3000:3000"
    networks:
      - metzner-app

  metzner-backend:
    container_name: metzner-backend
    image: metzner-backend
    ports:
      - "3001:3001"
    networks:
      - metzner-app

networks:
  metzner-app: {}
# docker-compose -f docker/docker-compose-dev.yaml up -d
