version: "3"

services:
  metzner-nginx:
    container_name: metzner-nginx
    image: ddrram/metzner-nginx-prod:1.0.0
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - metzner-frontend
      - metzner-backend
    networks:
      - metzner-app

  metzner-frontend:
    container_name: metzner-frontend
    image: ddrram/metzner-frontend:1.0.0
    ports:
      - "3000:3000"
    networks:
      - metzner-app

  metzner-backend:
    container_name: metzner-backend
    image: ddrram/metzner-backend:1.0.0
    ports:
      - "3001:3001"
    networks:
      - metzner-app

networks:
  metzner-app: {}
# docker-compose -f docker/docker-compose-prod.yaml up -d
