version: "3"

services:
  metzner-nginx:
    container_name: metzner-nginx
    image: ddrram/metzner-nginx-test:1.1.10 # 1.1.2 stabil
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - metzner-frontend
      - metzner-backend
    networks:
      - metzner-app
    volumes:
      - /root/usr/share/certbot/conf:/etc/letsencrypt

  metzner-frontend:
    container_name: metzner-frontend
    image: ddrram/metzner-frontend:1.1.3 # 1.1.2 stabil
    ports:
      - "3000:3000"
    networks:
      - metzner-app

  metzner-backend:
    container_name: metzner-backend
    image: ddrram/metzner-backend:1.1.0
    ports:
      - "3001:3001"
    networks:
      - metzner-app

networks:
  metzner-app: {}
# docker-compose -f docker/docker-compose-test.yaml up -d
